### ISSUE TITLE
Node usability

### ISSUE THREAD

**Issue by riovir** [elrumordelaluz/svgson-next#4]
Using version `2.4.0` in Node environment due to the `UMD` bundled format I needed to require the `default` prop from the library.
```JavaScript
const svgson = require('svgson-next').default;
```

A different mild surprise was that when passing in a single SVG string, I expected to get a parsed object, but got a singleton array instead.

```JavaScript
function parseSvg(svg) {
  return svgson(svg, {})
    .then(head)  // I needed to add this line
    .then(extractDetails);
}
```

**Comment by elrumordelaluz** [comment]
> Using version 2.4.0 in Node environment due to the UMD bundled format I needed to require the default prop from the library

For this I was dealing a little finding the best way to solve it with `webpack`, when added `.stringify` method to get back an `<svg />` string. 

I am thinking in change the build process, also help super welcome!

> .then(head)  // I needed to add this line

Don't understand at all what that line do.
However, yes returns always an `Array` because previously, using `htmlparser` the result was an array. I did [this](https://github.com/elrumordelaluz/svgson-next/blob/master/src/index.js#L46-L48) to maintain tests green, but should be an easy change, also something I like to apply since `svgson` does it.

Will give it an eye asap

**Comment by riovir** [comment]
>> .then(head) // I needed to add this line

> Don't understand at all what that line do.

It returns the first element of an array:
`function head(array) { return array[0]; }`

**Comment by elrumordelaluz** [comment]
@riovir could you give it a try with `svgson-next@3.0.0`

**Comment by riovir** [comment]
Updated, works as advertised. Thanks.
