### ISSUE TITLE
Pretty print option 

### ISSUE THREAD

**Issue by ceremcem** [elrumordelaluz/svgson-next#6]
It would be useful to have `prettyPrint: true` option for `stringify()` method when using revision control. Diffs will be created more human readable way, so we can inspect the changes more easily.

**Comment by elrumordelaluz** [comment]
absolutely @ceremcem! for now [the printer](https://github.com/pladaria/xml-printer) doesn't does that per se, but could be added as a custom function.

However I am always thinking between thos two sides:
> Add another cool feature

and

> Let the end-user pipe/plug the _output_ with whatever they want.

Based on the second one, I decided to drop [svgo](https://github.com/svg/svgo) optimizations as an internal _feature_, since from `v1` supports `Promises` and could be plugged with `svgson` easy, serving a [tiny bundle](https://bundlephobia.com/result?p=svgson-next@4.2.0) (compare `v3` vs `v4`) for those that don't need/want optimizations 

what do you think?

**Comment by ceremcem** [comment]
> However I am always thinking between those two sides:

Both works for me, but I would vote for *second option* if it is a *very distinct feature*.  However, if second option is the way to go, I think this functionality (proposed 3rd party library) should be mentioned in the documentation, possibly under "best practices" section.

**Comment by elrumordelaluz** [comment]
absolutely agree!
